### PR TITLE
removed Update Spec from the sidebar

### PR DESCRIPTION
**Pull request by alicelisisi**
i'm working on issue #33 

I just removed the associated html code, i checked and it worked fine. please let me know what more to remove.

### CODE REVIEW

**Comment by apsdehal** [comment]
Sorry for the confusion, can you read my comment on Piazza?

**Comment by alicelisisi** [comment]
Ok, now i've remove the spec editor.

**Comment by apsdehal** [comment]
Looks good, have you tested it on your side?

**Comment by alicelisisi** [comment]
yeah, i run locally, and it looked fine.

**Comment by apsdehal** [comment]
This has been merged. Thanks.

**Pull request merged**
